Add Japanese languagee
staniel359/muffon pull request #101
Opened 2023-04-06 16:05 UTC by maboroshin

Pull requests for Japanese language files only.

2023-04-06 16:13 UTC, staniel359 commented
@maboroshin So I guess you want to see your visualized translations.
But I can't release a version with incomplete translation.
You may want to setup and run muffon's local version?
I can give you the instructions.

2023-04-06 16:15 UTC, staniel359 requested changes

2023-04-06 16:15 UTC, staniel359 commented on src/plugins/i18n/locales/ja.json
> +  "electron": {
@maboroshin Please move Electron translations to `muffon/electron/plugins/i18n/locales` folder.

2023-04-06 16:24 UTC, maboroshin commented on src/plugins/i18n/locales/ja.json
> +  "electron": {
72% (145/510) : There are 510 texts, untranslated is 145.

2023-04-06 16:24 UTC, maboroshin commented
72% (145/510) : There are 510 texts, untranslated is 145.

2023-04-06 16:25 UTC, staniel359 commented
@maboroshin Okay, take your time.

2023-04-06 16:27 UTC, maboroshin commented
Other than mffon, I know of no other project that requires 100%.

2023-04-06 16:28 UTC, staniel359 commented
@maboroshin What do you mean?
Are there some English words that can't be translated to Japanese?

2023-04-06 16:30 UTC, maboroshin commented
The most stringent TRANSMISSION was based on 95%.

There is no English word that cannot be translated.
I am checking the actual display.  So mistranslations are unlikely to occur. This is why it takes time. It takes extra time to understand the untranslated parts.

2023-04-06 16:36 UTC, maboroshin commented on src/plugins/i18n/locales/ja.json
> +  "electron": {
@staniel359 I moved.

2023-04-06 16:38 UTC, staniel359 commented on src/plugins/i18n/locales/ja.json
> +  "electron": {
@maboroshin Still there.

2023-04-06 16:40 UTC, maboroshin commented
Sites using outside translation tools are often released with incomplete translations.
I sometimes don't make it 100% to avoid mistranslation.

2023-04-06 16:43 UTC, staniel359 commented
@maboroshin There should be no mistranslations as translations are grouped logically.

And this app uses 100% of the translations.

2023-04-06 16:44 UTC, maboroshin commented
Sites using outside translation tools are often released with incomplete translations.
I sometimes don't make it 100% to avoid mistranslation.

My Japanese translation of yattee is 97%. This is because I do not use this app. I do not translate without actually using it.
https://hosted.weblate.org/projects/yattee/localizable-strings/ja/

Check the translation status of Auto Dark mode. 100% is usually not maintained.
https://hosted.weblate.org/projects/yattee/localizable-strings/

2023-04-06 16:53 UTC, maboroshin commented on src/plugins/i18n/locales/ja.json
> +  "electron": {
It exists here in my browser.
![image](https://user-images.githubusercontent.com/41102508/230444742-0757d709-283a-42a8-9fe5-e767e6510d1a.png)

2023-04-06 16:58 UTC, maboroshin commented
Understood. I will abort.

2023-04-06 16:58 UTC, closed without merging

2023-04-06 17:00 UTC, staniel359 commented
@maboroshin Why?

2023-04-06 17:05 UTC, maboroshin commented
@staniel359 It takes time to find untranslated parts. This app has too much time than other software.
With indivious and Piped, all I have to do is translate the untranslated parts again, because a week later they show up in the actual UI.
I am checking to make sure I am not mistranslating. I have to use the app or read the source code to see where it appears.

2023-04-06 17:09 UTC, staniel359 commented
@maboroshin Okay, then please translate as much as possible.

And if you want to see your translations in action, I can create a test release with your translations for you.

2023-04-06 17:11 UTC, maboroshin commented
I'm in the middle of translating, but I saw the 1.5.0Update, so I did a pull request.

2023-04-06 17:42 UTC, staniel359 commented
@maboroshin So are you going to continue the translation?

2023-04-06 18:02 UTC, maboroshin commented
Umm... When it takes time, I move on to the next project once.

So far I have discontinued muffon and have completed 3 projects.
https://github.com/Moosync/Moosync
https://github.com/stephane-r/holoplay-pwa
https://github.com/amd64fox/SpotX

2023-04-06 18:03 UTC, staniel359 commented
@maboroshin Okay.

2023-06-11 13:35 UTC, staniel359 commented
@maboroshin Hello.
Maybe you would like to continue your translation?

2023-06-11 16:10 UTC, maboroshin commented
Hi! Is this the version that reflects the Japanese translation? If there is a Live version, I would like to do it.

2023-06-11 16:12 UTC, staniel359 commented
@maboroshin I haven't added Japanese language yet, but you can add and test it locally.
I can give you the instructions.

2023-06-11 16:37 UTC, maboroshin commented
OKey. if it is easy I will do it.

2023-06-11 16:51 UTC, staniel359 commented
@maboroshin
1. Install Node.js and Yarn
2. `git clone https://github.com/staniel359/muffon.git`
3. `cd muffon/`
4. Create `.env` file with `VITE_APP_ANONYMOUS_TOKEN=<some_random_token>` (then send me this token on my email)
5. In `src/plugins/axios.js` on line 3 change `const isDevelopment` to `false`
6. Add your translation files (`jp.json`) in `src/plugins/i18n/locales/` and `electron/plugins/i18n/locales/`
7. Search for `// i18n` in project folder and make changes in these files to add Japanese language.
8. `yarn`
9. `yarn start` (in one window)
10. `yarn start:electron` (in second window)

2023-06-11 17:09 UTC, maboroshin commented
Thank you. This information would be fine in the README.

I put off projects that take a long time. I will consider doing this after other time consuming projects.

2023-06-11 18:53 UTC, staniel359 commented
@maboroshin Okay.

2023-09-13 09:17 UTC, staniel359 commented
@maboroshin Hey, how's it going?
Would you like to continue your work maybe?

2023-11-12 05:30 UTC, xyloflake commented
Hey @maboroshin, I've added the Japanese language translation now, would like to test and rate it?

2023-11-12 06:51 UTC, maboroshin commented
Thank you. It was this one.
https://github.com/staniel359/muffon/blob/main/src/plugins/i18n/locales/ja.json

2023-11-12 08:35 UTC, xyloflake commented
@maboroshin I mean can you use the app and provide feedback for the translation? I have Japanese N1 qualification, but I'm not native so your feedback would be useful. You can change the language in settings.

2023-11-12 08:48 UTC, maboroshin commented
@xyloflake : I'm surprised that you are not native. You are better than a beginner translator. 
N1, This is the highest level of the Japanese-Language Proficiency Test!

---

Too many transliterations. So I apply more common Japanese. This will take time.

2023-11-12 12:02 UTC, xyloflake commented
@maboroshin はは、褒めてくれてありがとう。日本語は２ヶ月間勉強して、準備ができたと感じたら試験を受けたんだ。漢字は約４００個しか覚えられなかったけど、それで十分だったみたいで、今はN1の資格を持っているよ。それと、アプリを使ったことある？もし使ったら、もしエラーがあれば報告してくれると嬉しいな。エラーがなければ教えてくれて、今は開発者の一員として参加しているんだ（笑）。


Also sorry for using informal japanese if that offends you, I use that more often than formal one, so I am better at it 😅

2023-11-12 12:07 UTC, xyloflake commented
@maboroshin have you aborted by the way? Because I've translated everything.

2023-11-12 12:13 UTC, maboroshin commented
> have you aborted by the way? 

Staniel asked for 100% translation rate. So I aborted. So I have given this a low priority. But I'll take this opportunity to review it.

2023-11-12 12:16 UTC, xyloflake commented
@maboroshin thanks, do you have discord?