Remove unnecessary packaged dependencies
staniel359/muffon pull request #137
Opened 2024-01-08 18:24 UTC by xyloflake

Vue is not required after building. This reduces packaged app size by ~1.8 MB. Please test a build before merging.

2024-01-08 18:32 UTC, xyloflake commented
Just a lil’ extra reminder. Do NOT review without beta testing a build.

2024-01-08 20:04 UTC, gamersi submitted a review, later dismissed
LGTM
Works for me

2024-01-08 20:52 UTC, xyloflake commented
@gamersi please report packaged app size before/after the change.

2024-01-08 21:14 UTC, gamersi commented
# Delta & TL;DR:

| Format | DeltaSize |
|--------|--------|
| AppImage | **-3,3 MB** |
| unpacked | **-14,1 MB** |
| flatpak | **-1,1 MB** |
| rpm | **-0,9 MB** |
| pacman | **-3,3 MB** | 
| deb | **-3,3 MB** |

The difference for unpacked is - who would have thought - the largest coming in at 14,1 MB less disk usage

---
# Numbers
<details><summary>Details:</summary>
<p>

package sizes from `main` branch: 
AppImage: 133,1 MB
unpacked: 371,9 MB
flatpak: 87,8 MB
rpm: 83,8 MB
pacman: 122,6 MB
deb: 122,6 MB

package sizes from `xyloflake-dependencies-fix` branch:
AppImage: 129,8 MB
unpacked: 357,8 MB
flatpak: 86,7 MB
rpm: 82,9 MB
pacman: 119,3 MB
deb: 119,3 MB
</p>
</details>

2024-01-08 21:30 UTC, xyloflake commented
Yoohoo! That's a relief!

2024-01-09 09:39 UTC, staniel359 requested changes

2024-01-09 09:39 UTC, staniel359 commented on package.json
> +    "vue-router": "^4.2.5",
@xyloflake Please place them at the end, after vite dependencies (alphabetically).

2024-01-09 17:52 UTC, xyloflake commented on package.json
> +    "vue-router": "^4.2.5",
@staniel359 done.

2024-01-09 17:53 UTC, xyloflake commented
@gamersi @staniel359 please review.

2024-01-09 18:31 UTC, gamersi approved these changes
LGTM

2024-01-10 07:50 UTC, staniel359 approved these changes
LGTM

2024-01-10 07:51 UTC, merged