English corrections
staniel359/muffon pull request #210
Opened 2024-10-15 23:34 UTC by Lolabird

These are just small corrections to the English translation. 

There were some others that I wanted to fix just because they sounded a bit awkward to me (in the `going` section), but they are technically correct, so I left those as they were in the original. Let me know if you would like a pull request for those as well.

2024-10-16 07:30 UTC, xyloflake reviewed
Going good @Lolabird! 

Impressive work pointing out the mistakes and most of them look fine however the following need a little attention. 

Thank you for your significant contribution in advance 😄

2024-10-16 07:30 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
> +          "cachePages": "Cached pages",
This must be `Cache pages` because you will cache it if you choose, past tense is inappropriate.

2024-10-16 07:30 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
> +          "autoWarning": "Autoupdates on Linux are still in the experimental phase and may contain bugs.\nDuring the autoupdate process, the app will freeze temporarily.\nPlease avoid force-quitting
It should be `of` and not `on` as we are referring to a specific issue. Kindly revert. The addition of `please` is appreciated.

2024-10-16 07:30 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
> +            "description": "To connect to your Spotify account please follow [a link=guide]this guide[/a]."
Not *really* necessary. `Connecting your Spotify account` sounds more concise and direct than `Connecting to your Spotify account`.

2024-10-16 07:30 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
> +      "As such, I would like to ask for your help in supporting muffon.",
I think we can change "I" to "we" if @staniel359 permits has the dev team consists of 3 members now.

2024-10-16 07:30 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
>        "<strong>Would you like to make a donation?</strong>"
I also believe changing this to "Please consider making a donation." would sound better. @staniel359 please confirm.

2024-10-16 19:07 UTC, Lolabird commented
@xyloflake thanks for making the suggestions! I'll take a look and make adjustments and ask questions if I have any.

2024-10-16 19:08 UTC, Lolabird commented on src/plugins/i18n/locales/en.json
> +          "cachePages": "Cached pages",
Oh okay, I thought this was a description rather than a call to action. I'll change it back.

2024-10-16 19:18 UTC, Lolabird commented
@xyloflake Made all the changes except the one we're waiting for feedback on. Let me know when you'd like me to pull this out of draft status.

2024-10-16 19:22 UTC, xyloflake commented
> @xyloflake Made all the changes except the one we're waiting for feedback on.
Seems good @Lolabird, thank you for the amazing compliance 😄

We'll go ahead and wait for @staniel359 to respond.

> Let me know when you'd like me to pull this out of draft status.

Well, I would like you to decide when you want us to thoroughly review it and at the very end, when you have no changes to make anymore, you can pull this ou of draft 😄

2025-02-07 07:59 UTC, staniel359 requested changes

2025-02-07 07:59 UTC, staniel359 commented on src/plugins/i18n/locales/en.json
> +          "This will also delete the following data:",
@Lolabird Maybe "the following data of yours" would be better.

2025-02-07 07:59 UTC, staniel359 commented on src/plugins/i18n/locales/en.json
> +          "This will delete the following data:",
@Lolabird Same as above.

2025-02-07 07:59 UTC, staniel359 commented on src/plugins/i18n/locales/en.json
> +          "innerCounters": "Show muffon listeners counter",
@Lolabird It was intended to be plural.

2025-02-07 07:59 UTC, staniel359 commented on src/plugins/i18n/locales/en.json
> +      "As lot of time and effort were put into creating this project, it would be great to see that investment pay off.",
@Lolabird "As a lot" maybe?

2025-02-07 07:59 UTC, staniel359 commented on src/plugins/i18n/locales/en.json
>        "<strong>Would you like to make a donation?</strong>"
@xyloflake There are buttons after that question, that kind of answer it.
If it'd be a statement, buttons would seem off.

2025-02-21 22:33 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
> +          "This will also delete the following data:",
@staniel359 I think `of yours` is way too exaggerated.

2025-02-21 22:35 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
> +          "innerCounters": "Show muffon listeners counter",
@staniel359 why? Counters I believe shouldn't be plural and there's just one counter (singular) that counts the number of listeners (plural). Also two plurals must not be in the same sentence (listeners and counters).

2025-02-21 22:36 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
> +      "As lot of time and effort were put into creating this project, it would be great to see that investment pay off.",
I agree with this one

2025-02-21 22:42 UTC, staniel359 commented on src/plugins/i18n/locales/en.json
> +          "This will also delete the following data:",
@xyloflake Then how can we tell user that they're deleting their own data?

2025-02-22 12:01 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
> +          "This will also delete the following data:",
@staniel359 I think people understand that library, recommendations, playlists etc. are their data (which is to be deleted).

2025-02-22 15:41 UTC, staniel359 commented on src/plugins/i18n/locales/en.json
> +          "This will also delete the following data:",
@xyloflake Okay then.

2025-03-24 00:49 UTC, Lolabird commented on src/plugins/i18n/locales/en.json
>        "<strong>Would you like to make a donation?</strong>"
@staniel359 and @xyloflake should I leave this one as is, then?

2025-03-24 04:33 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
>        "<strong>Would you like to make a donation?</strong>"
@Lolabird I believe staniel is right here, please keep your changes intact :)

2025-03-24 04:35 UTC, xyloflake commented on src/plugins/i18n/locales/en.json
>        "<strong>Would you like to make a donation?</strong>"
@staniel359, just for the record, the changes are to be accepted right?

2025-03-24 07:12 UTC, staniel359 commented on src/plugins/i18n/locales/en.json
>        "<strong>Would you like to make a donation?</strong>"
@xyloflake @Lolabird Yes, should be left as is.

2025-03-24 07:15 UTC, staniel359 approved these changes

2025-03-24 11:17 UTC, xyloflake commented
Alright, LGTM, thanks @Lolabird for your contribution!

2025-03-24 11:17 UTC, xyloflake approved these changes

2025-03-24 11:18 UTC, merged