Add Chinese translations
staniel359/muffon pull request #212
Opened 2024-10-21 00:52 UTC by PoorShawn

A pull request to add Chinese translations to muffon.

2024-10-21 06:26 UTC, xyloflake commented
LGTM! @gamersi please approve accordingly.

Thank you for your valuable contribution @PoorShawn! We are much obliged.

2024-10-21 06:27 UTC, xyloflake approved these changes
LGTM! @gamersi please approve accordingly.

Thank you for your valuable contribution @PoorShawn! We are much obliged.

2024-10-21 08:32 UTC, gamersi approved these changes
Thanks! LGTM

2024-10-21 13:10 UTC, xyloflake submitted a review, later dismissed

2024-10-21 13:11 UTC, gamersi submitted a review, later dismissed

2024-10-21 13:12 UTC, xyloflake commented
Looks like we need a review from @staniel359

2025-02-07 08:04 UTC, staniel359 approved these changes, later dismissed

2025-02-08 11:10 UTC, xyloflake commented on src/plugins/i18n/locales/zh.json
> +    "sendCode": "发送验证码",
@PoorShawn should this not be `获取邮件验证码`? It's email code, just saying code is vague (I think).

2025-02-15 06:36 UTC, PoorShawn commented on src/plugins/i18n/locales/zh.json
> +    "sendCode": "发送验证码",
I agree with you ! Thanks for you detailed review ! Let me change it into `获取邮件验证码`

2025-02-15 08:01 UTC, staniel359 submitted a review, later dismissed

2025-02-15 08:13 UTC, xyloflake commented on src/plugins/i18n/locales/zh.json
> +    "sendCode": "发送验证码",
> I agree with you ! Thanks for you detailed review ! Let me change it into `获取邮件验证码`

Thank you! I'll have a deeper look so that we don't miss out on anything :)

2025-02-19 08:08 UTC, xyloflake requested changes
These are the last points I have to make @PoorShawn, just resolve these and we will be ready to merge!

2025-02-19 08:08 UTC, xyloflake commented on src/plugins/i18n/locales/zh.json
> +      "nickname": "呢称",
Shouldn't this be `昵称` @PoorShawn ?
Later in the file you use `昵` but here, it seems you've decided to use `呢`. Any reasoning behind that or is this a typo?

2025-02-19 08:08 UTC, xyloflake commented on src/plugins/i18n/locales/zh.json
> +          "infiniteScroll": "无线滚动",
This I think should be `无限滚动` as `无线滚动` would mean "infinite scrolling" but we want to say "infinite scroll"

2025-02-21 22:52 UTC, xyloflake commented
@PoorShawn we'd appreciate it if you address the raised concerns ASAP as we are planning to include your pr in our next release :)

2025-02-22 02:58 UTC, PoorShawn commented on src/plugins/i18n/locales/zh.json
> +      "nickname": "呢称",
@xyloflake Thanks for pointing that out! You’re right, I noticed the inconsistency. I’ll go ahead and change “呢称” to “昵称” to keep it consistent throughout the file.

2025-02-22 03:02 UTC, PoorShawn commented on src/plugins/i18n/locales/zh.json
> +          "infiniteScroll": "无线滚动",
Thanks for pointing that out! You're absolutely right. "无线滚动" doesn't quite convey the right meaning, and "无限滚动" is definitely the correct term for "infinite scroll". I’ll make that change.

2025-02-22 03:16 UTC, PoorShawn commented
@xyloflake Thanks for your patience! 😄I’ve made the necessary changes and updated the PR. Please feel free to check it out whenever you have a chance.

2025-02-22 05:01 UTC, xyloflake commented on src/plugins/i18n/locales/zh.json
> +          "infiniteScroll": "无线滚动",
Thanks!

2025-02-22 05:01 UTC, xyloflake commented on src/plugins/i18n/locales/zh.json
> +      "nickname": "呢称",
Thank you!

2025-02-22 05:02 UTC, xyloflake approved these changes
LGTM, thank you Shawn!

2025-02-22 07:56 UTC, gamersi approved these changes

2025-02-22 07:57 UTC, merged

2025-02-22 07:58 UTC, xyloflake commented
Congratulations @PoorShawn! Your PR has been merged and will be included in our next release!