Add Italian language
staniel359/muffon pull request #64
Opened 2022-09-08 12:46 UTC by ZinRicky

- Add Italian support in README.
- Add Italian translation for both app and Electron.
- Improve translation of some terms, following Spotify’s standards (e.g. “tracks” → “brani” instead of “tracks” → “tracce”.

2022-09-08 12:47 UTC, ZinRicky commented
PS: sorry for the closure of the other PR. I made a mistake and lost every change

2022-09-08 15:18 UTC, staniel359 requested changes
@ZinRicky Please address these changes.

2022-09-08 15:18 UTC, staniel359 commented on README.md
> +- Italiano
@ZinRicky This file will be updated after new version is released.
Please remove this line for now.

2022-09-10 10:08 UTC, staniel359 approved these changes

2022-09-10 10:09 UTC, staniel359 commented
@ZinRicky Great job, thank you.

2022-09-10 10:09 UTC, merged

2022-09-10 13:08 UTC, filipporomani commented
Oooooof
I started translasting this 2 days ago, almost 25% done lol
Better luck next time!

2022-09-10 14:57 UTC, staniel359 commented
@filipporomani That's good too.
You can check out ZinRicky's work and make your changes to it.
Or you both can cooperate.

2022-09-10 18:01 UTC, staniel359 commented
@ZinRicky @filipporomani By the way, your help's needed [here](https://github.com/staniel359/muffon-website) too.
Does anybody want to translate the website part as well?

2022-09-10 18:03 UTC, filipporomani commented
Sure! I'm not able to start that right now, btw can u send me a link to the repo? 
Thanks!

2022-09-10 18:06 UTC, staniel359 commented
@filipporomani https://github.com/staniel359/muffon-website

2022-09-10 21:26 UTC, filipporomani commented
Done! Json file translated

2022-09-11 08:55 UTC, staniel359 commented
@filipporomani Thank you, wrote you there.

2022-09-17 09:01 UTC, staniel359 commented
@ZinRicky @filipporomani Maybe some of you want to translate [this one](https://github.com/staniel359/muffon-api/blob/main/config/locales/en.yml) too?

2022-09-17 09:16 UTC, ZinRicky commented
> @ZinRicky @filipporomani Maybe somebody wants to translate [this one](https://github.com/staniel359/muffon-api/blob/main/config/locales/en.yml) too?

Since it seems quite easy, here

[it.zip](https://github.com/staniel359/muffon/files/9591330/it.zip)

2022-09-17 09:43 UTC, staniel359 commented
@ZinRicky Nice, thank you.

2022-09-17 12:07 UTC, filipporomani commented
Sure! When I'll be back home I'll translate it!

Il sab 17 set 2022, 11:01 Aleksey Shpakovsky ***@***.***> ha
scritto:

> @ZinRicky <https://github.com/ZinRicky> @filipporomani
> <https://github.com/filipporomani> Maybe some of you want to translate this
> one
> <https://github.com/staniel359/muffon-api/blob/main/config/locales/en.yml>
> too?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/staniel359/muffon/pull/64#issuecomment-1250032975>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARKKPKIJ3V3P2KDH5ZMP4FTV6WCGPANCNFSM6AAAAAAQHWWDBQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-09-17 12:54 UTC, staniel359 commented
@filipporomani Sorry, already translated.