New italian translation
staniel359/muffon pull request #75
Opened 2022-11-12 15:49 UTC by filipporomani

Everything should be updated now.

2022-11-12 16:14 UTC, staniel359 commented
@filipporomani Please update your local repo.

2022-11-13 11:41 UTC, staniel359 requested changes
@filipporomani Please take a look.

2022-11-13 11:41 UTC, staniel359 commented on shared/locales/it.json
> -    "recommendations": "Suggerimenti",
@filipporomani This one shouldn't be removed.
The actual one is on line 537.

2022-11-13 11:41 UTC, staniel359 commented on shared/locales/it.json
> +    "filter": "Filtra",
@filipporomani Please keep the original order of the keys.

2022-11-17 16:42 UTC, staniel359 commented
@ZinRicky Hello.
How's your computer?

2022-11-19 14:27 UTC, staniel359 commented
@starise Hello. Would you like to help with the translation?

2022-11-19 23:30 UTC, staniel359 commented
@filipporomani Hello.
Could you take a look at my notes?

2022-11-20 11:03 UTC, ZinRicky commented
> @ZinRicky Hello. How's your computer?

Not well, unfortunately. The mobo short-circuited, and the bill is ~1000€, which I don’t have at the moment.

2022-11-20 11:06 UTC, staniel359 commented
@ZinRicky Too bad.
So you won't be able to complete the translation?

2022-11-20 11:21 UTC, ZinRicky commented
I’m afraid I won’t. I don’t have a PC of mine at disposal

2022-11-20 11:24 UTC, filipporomani commented
Hello, currently I'm a bit confused about the modifications to do. I almost never worked on GH PRs and I don't understand the comparison.

2022-11-20 11:24 UTC, filipporomani commented
Hello, currently I'm a bit confused about the modifications to do. I almost never worked on GH PRs and I don't understand the comparison.

2022-11-20 11:32 UTC, staniel359 commented
@ZinRicky I see.
Well, I hope you'll solve your problem.

2022-11-20 11:34 UTC, staniel359 commented
@filipporomani Okay.
Then could you just create another PR?
There are no more modifications so far.

2022-11-20 12:37 UTC, staniel359 commented
@filipporomani Just wanted to release a new version, and I'd really appreciate if you complete Italian translation.

2022-11-20 17:16 UTC, staniel359 commented
@filipporomani Just wanted to release a new version, and I'd really appreciate if you complete Italian translation.

2022-11-21 10:45 UTC, filipporomani commented
Created #79, refer to that from now.

2022-11-21 10:45 UTC, closed without merging

2023-01-24 19:21 UTC, staniel359 commented
@ZinRicky Hello.
If your don't have a computer yet, is there a chance that you have mobile Discord?
So you could help me with translations there.

2023-08-02 13:48 UTC, staniel359 commented
@ZinRicky Hey, how's it going?