Update italian translation
staniel359/muffon pull request #90
Opened 2023-01-18 19:06 UTC by filipporomani

2023-01-18 19:22 UTC, staniel359 requested changes

2023-01-18 19:22 UTC, staniel359 commented on shared/plugins/i18n/locales/it.json
> +      },
@filipporomani Please fix indentation here.

2023-01-18 19:22 UTC, staniel359 commented on shared/plugins/i18n/locales/it.json
> +          "account": {
@filipporomani Please fix indentation here as well.

2023-01-20 19:55 UTC, filipporomani reviewed
Everything should be ok now.

2023-01-20 21:17 UTC, staniel359 commented
@filipporomani Please also check this one:
https://github.com/staniel359/muffon/commit/8b0ba83c68f52fa0275ef12b8e7b89d6d8f9b5b1#diff-82f3a9ef205a33dc1be103814db2824b7ac6ac048c75697c5b17a789a7381044

2023-01-23 11:06 UTC, staniel359 approved these changes
@filipporomani Thank you.

2023-01-23 11:07 UTC, merged